# Generated by Django 5.1.6 on 2025-03-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(max_length=100)),
                ('spouse', models.CharField(blank=True, default='Single', max_length=100, null=True)),
                ('role', models.CharField(max_length=50)),
                ('batting_style', models.CharField(max_length=50)),
                ('bowling_style', models.CharField(max_length=50)),
                ('image', models.ImageField(default='players/default.png', upload_to='players/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BowlingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=10)),
                ('matches', models.IntegerField(default=0)),
                ('innings', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0.0)),
                ('economy', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_stats', to='cric.player')),
            ],
        ),
        migrations.CreateModel(
            name='BattingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=10)),
                ('matches', models.IntegerField(default=0)),
                ('innings', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0.0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_stats', to='cric.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cric.team'),
        ),
    ]
