# Generated by Django 5.1.6 on 2025-03-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0002_player_team_bowlingstats_battingstats_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('feed', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='bowlingstats',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.DeleteModel(
            name='BattingStats',
        ),
        migrations.DeleteModel(
            name='BowlingStats',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
